#!/usr/bin/env python3
"""isayscribe Lite — Dictate Text → Create Note. No API. No AI. Just works."""
import plistlib, uuid, os, subprocess

BASE = "/Users/clementsemerson/isayscribe"

def uid():
    return str(uuid.uuid4()).upper()

U_DICT = uid()
U_NOTE = uid()

def tok_attach(out_uuid, out_name):
    return {
        "Value": {"OutputUUID": out_uuid, "OutputName": out_name, "Type": "ActionOutput"},
        "WFSerializationType": "WFTextTokenAttachment",
    }

actions = [
    {
        "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
        "WFWorkflowActionParameters": {
            "UUID": uid(),
            "WFCommentActionText": "Shortcuts generated by Shortcuts Playground.\nisayscribe Lite — No API. No AI. Just dictation to notes.",
        },
    },
    {
        "WFWorkflowActionIdentifier": "is.workflow.actions.dictatetext",
        "WFWorkflowActionParameters": {"UUID": U_DICT},
    },
    {
        "WFWorkflowActionIdentifier": "com.apple.mobilenotes.SharingExtension",
        "WFWorkflowActionParameters": {
            "UUID": U_NOTE,
            "AppIntentDescriptor": {"AppIntentIdentifier": "com.apple.mobilenotes.SharingExtension"},
            "name": "isayscribe",
            "content": tok_attach(U_DICT, "Dictated Text"),
        },
    },
]

workflow = {
    "WFWorkflowActions": actions,
    "WFWorkflowClientVersion": "710",
    "WFWorkflowClientRelease": "2.1",
    "WFWorkflowIcon": {
        "WFWorkflowIconGlyphNumber": 61440,
        "WFWorkflowIconStartColor": 4282601983,
    },
    "WFWorkflowImportQuestions": [],
    "WFWorkflowMinimumClientVersion": 900,
    "WFWorkflowName": "isayscribe Lite",
    "WFWorkflowTypes": ["NCWidget", "WatchKit", "ActionExtension"],
}

out_path = os.path.join(BASE, "isayscribe-Lite.shortcut")
with open(out_path, "wb") as f:
    plistlib.dump(workflow, f, fmt=plistlib.FMT_XML)
subprocess.run(["plutil", "-convert", "binary1", out_path, "-o", out_path], check=True)

print(f"Wrote: {out_path}")
print("Actions: Dictate Text → Create Note")
