#!/usr/bin/env python3
"""isayscribe v3.5 — Text action bridge between Dictate and Llama JSON."""
import plistlib, uuid, os, subprocess

BASE = "/Users/clementsemerson/isayscribe"

with open(os.path.join(BASE, "prompt.txt"), "r", encoding="utf-8") as f:
    SYSTEM_PROMPT = f.read()

def uid():
    return str(uuid.uuid4()).upper()

U_C1 = uid(); U_C2 = uid(); U_C3 = uid()
U_KEY  = uid()   # Text: API key
U_DICT = uid()   # Dictate Text
U_BRIDGE = uid() # Text: bridge holding dictation
U_DL   = uid()   # Llama downloadurl
U_GET  = uid()   # getvalueforkey
U_NOTE = uid()   # Create Note

def tts_attach(out_uuid, out_name):
    """WFTextTokenString with single U+FFFC at position 0."""
    return {
        "Value": {
            "attachmentsByRange": {"{0, 1}": {"OutputUUID": out_uuid, "OutputName": out_name, "Type": "ActionOutput"}},
            "string": "\ufffc",
        },
        "WFSerializationType": "WFTextTokenString",
    }

def tta_attach(out_uuid, out_name):
    return {
        "Value": {"OutputUUID": out_uuid, "OutputName": out_name, "Type": "ActionOutput"},
        "WFSerializationType": "WFTextTokenAttachment",
    }

def wf_kv(key, item_type, value):
    return {"UUID": uid(), "WFKey": {"Value": {"string": key}, "WFSerializationType": "WFTextTokenString"}, "WFItemType": item_type, "WFValue": value}

def wf_text(val):
    return {"Value": {"string": val}, "WFSerializationType": "WFTextTokenString"}

def wf_dict_val(items):
    return {"Value": {"WFDictionaryFieldValueItems": items}, "WFSerializationType": "WFDictionaryFieldValue"}

actions = [
    {"WFWorkflowActionIdentifier": "is.workflow.actions.comment", "WFWorkflowActionParameters": {
        "UUID": U_C1, "WFCommentActionText": "Shortcuts generated by Shortcuts Playground.\nisayscribe — Speak, get a formatted note."}},
    {"WFWorkflowActionIdentifier": "is.workflow.actions.comment", "WFWorkflowActionParameters": {
        "UUID": U_C2, "WFCommentActionText": "Shortcuts generated by Shortcuts Playground.\nEdit the Text action below: replace gsk_YOUR_KEY with your actual Groq key."}},
    {"WFWorkflowActionIdentifier": "is.workflow.actions.comment", "WFWorkflowActionParameters": {
        "UUID": U_C3, "WFCommentActionText": "Wiring: Dictate → Text bridge → Llama JSON body → Create Note."}},
    # Text: API key
    {"WFWorkflowActionIdentifier": "is.workflow.actions.gettext", "WFWorkflowActionParameters": {
        "UUID": U_KEY, "WFTextActionText": "Bearer gsk_YOUR_KEY"}},
    # Dictate Text
    {"WFWorkflowActionIdentifier": "is.workflow.actions.dictatetext", "WFWorkflowActionParameters": {"UUID": U_DICT}},
    # Text: bridge action holding the dictation
    {"WFWorkflowActionIdentifier": "is.workflow.actions.gettext", "WFWorkflowActionParameters": {
        "UUID": U_BRIDGE,
        "WFTextActionText": tts_attach(U_DICT, "Dictated Text"),
    }},
    # Llama-3.3 (JSON body)
    {"WFWorkflowActionIdentifier": "is.workflow.actions.downloadurl", "WFWorkflowActionParameters": {
        "UUID": U_DL,
        "WFURL": "https://api.groq.com/openai/v1/chat/completions",
        "WFHTTPMethod": "POST",
        "WFHTTPBodyType": "JSON",
        "WFHTTPHeaders": wf_dict_val([
            wf_kv("Authorization", 0, tta_attach(U_KEY, "Text")),
            wf_kv("Content-Type", 0, wf_text("application/json")),
        ]),
        "WFJSONValues": wf_dict_val([
            wf_kv("model", 0, wf_text("llama-3.3-70b-versatile")),
            wf_kv("messages", 2, {"Value": [
                {"WFItemType": 1, "WFValue": wf_dict_val([
                    wf_kv("role", 0, wf_text("system")),
                    wf_kv("content", 0, wf_text(SYSTEM_PROMPT)),
                ])},
                {"WFItemType": 1, "WFValue": wf_dict_val([
                    wf_kv("role", 0, wf_text("user")),
                    wf_kv("content", 0, tta_attach(U_BRIDGE, "Text")),
                ])},
            ], "WFSerializationType": "WFArrayParameterState"}),
        ]),
        "ShowHeaders": True, "Advanced": True,
        "WFAllowsCellularAccess": 1, "WFAllowsRedirects": 1, "WFIgnoreCookies": 0, "WFTimeout": 120,
    }},
    # Get choices.1.message.content
    {"WFWorkflowActionIdentifier": "is.workflow.actions.getvalueforkey", "WFWorkflowActionParameters": {
        "UUID": U_GET, "WFDictionaryKey": "choices.1.message.content", "WFGetDictionaryValueType": "Value",
        "WFInput": tta_attach(U_DL, "Contents of URL"),
    }},
    # Create Note
    {"WFWorkflowActionIdentifier": "com.apple.mobilenotes.SharingExtension", "WFWorkflowActionParameters": {
        "UUID": U_NOTE, "AppIntentDescriptor": {"AppIntentIdentifier": "com.apple.mobilenotes.SharingExtension"},
        "name": "isayscribe - New Idea",
        "content": tta_attach(U_GET, "Dictionary Value"),
    }},
]

workflow = {
    "WFWorkflowActions": actions,
    "WFWorkflowClientVersion": "710", "WFWorkflowClientRelease": "2.1",
    "WFWorkflowIcon": {"WFWorkflowIconGlyphNumber": 61440, "WFWorkflowIconStartColor": 4282601983},
    "WFWorkflowImportQuestions": [],
    "WFWorkflowMinimumClientVersion": 900,
    "WFWorkflowName": "isayscribe",
    "WFWorkflowTypes": ["NCWidget", "WatchKit", "ActionExtension"],
}

out_path = os.path.join(BASE, "isayscribe.shortcut")
with open(out_path, "wb") as f:
    plistlib.dump(workflow, f, fmt=plistlib.FMT_XML)
subprocess.run(["plutil", "-convert", "binary1", out_path, "-o", out_path], check=True)
print("Built v3.5: Dictate → Text bridge → Llama JSON → Create Note")
