#!/usr/bin/env python3
"""Generate isayscribe.shortcut — passes shortcuts-playground validator."""
import plistlib
import uuid
import os

BASE = "/Users/clementsemerson/isayscribe"

with open(os.path.join(BASE, "prompt.txt"), "r", encoding="utf-8") as f:
    SYSTEM_PROMPT = f.read()

def uid():
    return str(uuid.uuid4()).upper()

API_KEY = "Bearer YOUR_GROQ_API_KEY_HERE"
WHISPER_URL = "https://api.groq.com/openai/v1/audio/transcriptions"
LLAMA_URL = "https://api.groq.com/openai/v1/chat/completions"

# ——— UUIDs ———
U_CMT0  = uid()  # comment 0: description
U_CMT1  = uid()  # comment 1: prompt block
U_CMT2  = uid()  # comment 2: section wiring
U_REC    = uid()  # recordaudio
U_WHISP  = uid()  # downloadurl Whisper
U_TXT    = uid()  # getvalueforkey "text"
U_LLAMA  = uid()  # downloadurl Llama
U_CHOICE = uid()  # getvalueforkey "choices.1.message.content"
U_NOTE   = uid()  # Create Note

# ——— Helpers ———

def tok_attach(out_uuid, out_name):
    """WFTextTokenAttachment: reference an action output."""
    return {
        "Value": {"OutputUUID": out_uuid, "OutputName": out_name, "Type": "ActionOutput"},
        "WFSerializationType": "WFTextTokenAttachment",
    }

def wf_kv(key, item_type, value):
    return {
        "UUID": uid(),
        "WFKey": {"Value": {"string": key}, "WFSerializationType": "WFTextTokenString"},
        "WFItemType": item_type,
        "WFValue": value,
    }

def wf_text(val):
    """WFItemType 0 — plain text."""
    return {"Value": {"string": val}, "WFSerializationType": "WFTextTokenString"}

def wf_file_ref(out_uuid):
    """WFItemType 5 — file reference for Form body."""
    return {
        "Value": {"Type": "ActionOutput", "OutputUUID": out_uuid, "OutputName": "Recorded Audio"},
        "WFSerializationType": "WFTokenAttachmentParameterState",
    }

def wf_dict_val(items):
    return {
        "Value": {"WFDictionaryFieldValueItems": items},
        "WFSerializationType": "WFDictionaryFieldValue",
    }

def wf_headers(hdrs):
    return wf_dict_val([wf_kv(k, 0, wf_text(v)) for k, v in hdrs.items()])

def wf_json_messages():
    """messages array for chat completions: [system dict, user dict]."""
    return {
        "Value": [
            # system message
            {
                "WFItemType": 1,
                "WFValue": wf_dict_val([
                    wf_kv("role", 0, wf_text("system")),
                    wf_kv("content", 0, wf_text(SYSTEM_PROMPT)),
                ]),
            },
            # user message — content references the transcript dictionary value
            {
                "WFItemType": 1,
                "WFValue": wf_dict_val([
                    wf_kv("role", 0, wf_text("user")),
                    wf_kv("content", 0, tok_attach(U_TXT, "Dictionary Value")),
                ]),
            },
        ],
        "WFSerializationType": "WFArrayParameterState",
    }

# ——— Actions ———

actions = []

# 0: Comment — shortcut description
actions.append({
    "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
    "WFWorkflowActionParameters": {
        "UUID": U_CMT0,
        "WFCommentActionText": (
            "isayscribe — Record audio, transcribe via Groq Whisper, "
            "format with Llama-3.3, save to Apple Notes."
        ),
    },
})

# 1: Comment — required Shortcuts Playground prompt block
actions.append({
    "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
    "WFWorkflowActionParameters": {
        "UUID": U_CMT1,
        "WFCommentActionText": (
            "Shortcuts generated by Shortcuts Playground.\n"
            "Record audio → Whisper transcription → Llama-3.3 formatting → Apple Notes.\n"
            "Set your Groq API key (gsk_) when importing this shortcut."
        ),
    },
})

# 2: Comment — section wiring notes
actions.append({
    "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
    "WFWorkflowActionParameters": {
        "UUID": U_CMT2,
        "WFCommentActionText": (
            "Wiring:\n"
            "- Whisper call uses Form body with file upload for the audio\n"
            "- Transcript text extracted via Get Dictionary Value ('text')\n"
            "- Llama call uses JSON body with messages array\n"
            "- Final output extracted via Get Dictionary Value ('choices.1.message.content')\n"
            "- Saved to Apple Notes via Create Note"
        ),
    },
})

# 3: Record Audio
actions.append({
    "WFWorkflowActionIdentifier": "is.workflow.actions.recordaudio",
    "WFWorkflowActionParameters": {"UUID": U_REC},
})

# 4: Download URL — Groq Whisper (Form, POST)
actions.append({
    "WFWorkflowActionIdentifier": "is.workflow.actions.downloadurl",
    "WFWorkflowActionParameters": {
        "UUID": U_WHISP,
        "WFURL": WHISPER_URL,
        "WFHTTPMethod": "POST",
        "WFHTTPBodyType": "Form",
        "WFHTTPHeaders": wf_headers({"Authorization": API_KEY}),
        "WFFormValues": wf_dict_val([
            wf_kv("file", 5, wf_file_ref(U_REC)),
            wf_kv("model", 0, wf_text("whisper-large-v3")),
            wf_kv("response_format", 0, wf_text("json")),
        ]),
        "ShowHeaders": True,
        "Advanced": True,
        "WFAllowsCellularAccess": 1,
        "WFAllowsRedirects": 1,
        "WFIgnoreCookies": 0,
        "WFTimeout": 60,
    },
})

# 5: Get Dictionary Value — "text" from Whisper response
actions.append({
    "WFWorkflowActionIdentifier": "is.workflow.actions.getvalueforkey",
    "WFWorkflowActionParameters": {
        "UUID": U_TXT,
        "WFDictionaryKey": "text",
        "WFGetDictionaryValueType": "Value",
        "WFInput": tok_attach(U_WHISP, "Contents of URL"),
    },
})

# 6: Download URL — Groq Llama-3.3 chat completions (JSON, POST)
actions.append({
    "WFWorkflowActionIdentifier": "is.workflow.actions.downloadurl",
    "WFWorkflowActionParameters": {
        "UUID": U_LLAMA,
        "WFURL": LLAMA_URL,
        "WFHTTPMethod": "POST",
        "WFHTTPBodyType": "JSON",
        "WFHTTPHeaders": wf_headers({
            "Authorization": API_KEY,
            "Content-Type": "application/json",
        }),
        "WFJSONValues": wf_dict_val([
            wf_kv("model", 0, wf_text("llama-3.3-70b-specdec")),
            wf_kv("messages", 2, wf_json_messages()),
        ]),
        "ShowHeaders": True,
        "Advanced": True,
        "WFAllowsCellularAccess": 1,
        "WFAllowsRedirects": 1,
        "WFIgnoreCookies": 0,
        "WFTimeout": 120,
    },
})

# 7: Get Dictionary Value — "choices.1.message.content" from Llama response
actions.append({
    "WFWorkflowActionIdentifier": "is.workflow.actions.getvalueforkey",
    "WFWorkflowActionParameters": {
        "UUID": U_CHOICE,
        "WFDictionaryKey": "choices.1.message.content",
        "WFGetDictionaryValueType": "Value",
        "WFInput": tok_attach(U_LLAMA, "Contents of URL"),
    },
})

# 8: Create Note (ToolKit AppIntent)
actions.append({
    "WFWorkflowActionIdentifier": "com.apple.mobilenotes.SharingExtension",
    "WFWorkflowActionParameters": {
        "UUID": U_NOTE,
        "AppIntentDescriptor": {
            "AppIntentIdentifier": "com.apple.mobilenotes.SharingExtension",
        },
        "name": "isayscribe - New Idea",
        "content": tok_attach(U_CHOICE, "Dictionary Value"),
    },
})

# ——— Workflow plist ———
workflow = {
    "WFWorkflowActions": actions,
    "WFWorkflowClientVersion": "710",
    "WFWorkflowClientRelease": "2.1",
    "WFWorkflowIcon": {
        "WFWorkflowIconGlyphNumber": 61440,
        "WFWorkflowIconStartColor": 4282601983,
    },
    "WFWorkflowImportQuestions": [
        {
            "Category": "Parameter",
            "ActionIndex": 4,
            "ParameterKey": "WFHTTPHeaders",
            "Text": "Your Groq API Key (starts with gsk_)",
            "DefaultValue": "",
        },
        {
            "Category": "Parameter",
            "ActionIndex": 6,
            "ParameterKey": "WFHTTPHeaders",
            "Text": "Your Groq API Key (same as above)",
            "DefaultValue": "",
        },
    ],
    "WFWorkflowMinimumClientVersion": 900,
    "WFWorkflowName": "isayscribe",
    "WFWorkflowTypes": ["NCWidget", "WatchKit", "ActionExtension"],
}

out_path = os.path.join(BASE, "isayscribe.shortcut")
with open(out_path, "wb") as f:
    plistlib.dump(workflow, f, fmt=plistlib.FMT_XML)

# Convert to binary plist (required before signing)
import subprocess
subprocess.run(["plutil", "-convert", "binary1", out_path, "-o", out_path], check=True)

print(f"Wrote: {out_path}  (binary plist)")
print(f"Actions: {len(actions)}")
print()
print("Next:  shortcuts sign --input {out} --output {out} --mode anyone".format(out=out_path))
