#!/usr/bin/env python3
"""isayscribe v3 — native iOS transcription + Groq Llama formatting."""
import plistlib, uuid, os, subprocess

BASE = "/Users/clementsemerson/isayscribe"

with open(os.path.join(BASE, "prompt.txt"), "r", encoding="utf-8") as f:
    SYSTEM_PROMPT = f.read()

API_KEY = "Bearer YOUR_GROQ_API_KEY_HERE"

def uid():
    return str(uuid.uuid4()).upper()

# UUIDs
U_CMT0  = uid()
U_CMT1  = uid()
U_CMT2  = uid()
U_REC   = uid()
U_TRANS = uid()   # Native Transcribe Audio
U_LLAMA = uid()   # Llama downloadurl
U_CHOICE = uid()  # getvalueforkey
U_NOTE  = uid()   # Create Note

def tok_attach(out_uuid, out_name):
    return {
        "Value": {"OutputUUID": out_uuid, "OutputName": out_name, "Type": "ActionOutput"},
        "WFSerializationType": "WFTextTokenAttachment",
    }

def wf_kv(key, item_type, value):
    return {
        "UUID": uid(), "WFKey": {"Value": {"string": key}, "WFSerializationType": "WFTextTokenString"},
        "WFItemType": item_type, "WFValue": value,
    }

def wf_text(val):
    return {"Value": {"string": val}, "WFSerializationType": "WFTextTokenString"}

def wf_dict_val(items):
    return {"Value": {"WFDictionaryFieldValueItems": items}, "WFSerializationType": "WFDictionaryFieldValue"}

def wf_headers(hdrs):
    return wf_dict_val([wf_kv(k, 0, wf_text(v)) for k, v in hdrs.items()])

def wf_json_messages():
    return {
        "Value": [
            {
                "WFItemType": 1,
                "WFValue": wf_dict_val([
                    wf_kv("role", 0, wf_text("system")),
                    wf_kv("content", 0, wf_text(SYSTEM_PROMPT)),
                ]),
            },
            {
                "WFItemType": 1,
                "WFValue": wf_dict_val([
                    wf_kv("role", 0, wf_text("user")),
                    wf_kv("content", 0, tok_attach(U_TRANS, "Text")),
                ]),
            },
        ],
        "WFSerializationType": "WFArrayParameterState",
    }

actions = [
    # Comment 0: description
    {
        "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
        "WFWorkflowActionParameters": {
            "UUID": U_CMT0,
            "WFCommentActionText": "isayscribe — Record audio, transcribe on-device, format with Llama-3.3, save to Apple Notes.",
        },
    },
    # Comment 1: Shortcuts Playground prompt block
    {
        "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
        "WFWorkflowActionParameters": {
            "UUID": U_CMT1,
            "WFCommentActionText": "Shortcuts generated by Shortcuts Playground.\nRecord audio → Native transcription → Llama-3.3 formatting → Apple Notes.\nSet your Groq API key (gsk_) when importing this shortcut.",
        },
    },
    # Comment 2: wiring notes
    {
        "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
        "WFWorkflowActionParameters": {
            "UUID": U_CMT2,
            "WFCommentActionText": "Wiring:\n- Record Audio output goes directly to Transcribe Audio\n- Transcribed text is sent as user message to Llama-3.3\n- Llama response formatted via Get Dictionary Value\n- Final output saved to Apple Notes via Create Note",
        },
    },
    # Record Audio
    {
        "WFWorkflowActionIdentifier": "is.workflow.actions.recordaudio",
        "WFWorkflowActionParameters": {"UUID": U_REC},
    },
    # Transcribe Audio (native iOS, on-device)
    {
        "WFWorkflowActionIdentifier": "com.apple.ShortcutsActions.TranscribeAudioAction",
        "WFWorkflowActionParameters": {
            "UUID": U_TRANS,
            "AppIntentDescriptor": {"AppIntentIdentifier": "com.apple.ShortcutsActions.TranscribeAudioAction"},
            "audio": tok_attach(U_REC, "Recorded Audio"),
        },
    },
    # Llama-3.3 chat completions (JSON POST)
    {
        "WFWorkflowActionIdentifier": "is.workflow.actions.downloadurl",
        "WFWorkflowActionParameters": {
            "UUID": U_LLAMA,
            "WFURL": "https://api.groq.com/openai/v1/chat/completions",
            "WFHTTPMethod": "POST",
            "WFHTTPBodyType": "JSON",
            "WFHTTPHeaders": wf_headers({
                "Authorization": API_KEY,
                "Content-Type": "application/json",
            }),
            "WFJSONValues": wf_dict_val([
                wf_kv("model", 0, wf_text("llama-3.3-70b-versatile")),
                wf_kv("messages", 2, wf_json_messages()),
            ]),
            "ShowHeaders": True,
            "Advanced": True,
            "WFAllowsCellularAccess": 1,
            "WFAllowsRedirects": 1,
            "WFIgnoreCookies": 0,
            "WFTimeout": 120,
        },
    },
    # Get Dictionary Value: "choices.1.message.content"
    {
        "WFWorkflowActionIdentifier": "is.workflow.actions.getvalueforkey",
        "WFWorkflowActionParameters": {
            "UUID": U_CHOICE,
            "WFDictionaryKey": "choices.1.message.content",
            "WFGetDictionaryValueType": "Value",
            "WFInput": tok_attach(U_LLAMA, "Contents of URL"),
        },
    },
    # Create Note
    {
        "WFWorkflowActionIdentifier": "com.apple.mobilenotes.SharingExtension",
        "WFWorkflowActionParameters": {
            "UUID": U_NOTE,
            "AppIntentDescriptor": {"AppIntentIdentifier": "com.apple.mobilenotes.SharingExtension"},
            "name": "isayscribe - New Idea",
            "content": tok_attach(U_CHOICE, "Dictionary Value"),
        },
    },
]

workflow = {
    "WFWorkflowActions": actions,
    "WFWorkflowClientVersion": "710",
    "WFWorkflowClientRelease": "2.1",
    "WFWorkflowIcon": {
        "WFWorkflowIconGlyphNumber": 61440,
        "WFWorkflowIconStartColor": 4282601983,
    },
    "WFWorkflowImportQuestions": [
        {
            "Category": "Parameter", "ActionIndex": 5, "ParameterKey": "WFHTTPHeaders",
            "Text": "Your Groq API Key (starts with gsk_)", "DefaultValue": "",
        },
    ],
    "WFWorkflowMinimumClientVersion": 900,
    "WFWorkflowName": "isayscribe",
    "WFWorkflowTypes": ["NCWidget", "WatchKit", "ActionExtension"],
}

out_path = os.path.join(BASE, "isayscribe.shortcut")
with open(out_path, "wb") as f:
    plistlib.dump(workflow, f, fmt=plistlib.FMT_XML)
subprocess.run(["plutil", "-convert", "binary1", out_path, "-o", out_path], check=True)

print(f"Wrote binary plist: {out_path}")
print("Actions (8): Comment×3 → Record Audio → Transcribe Audio → Llama → Get Dict Key → Create Note")
print()
print(f"Sign:  shortcuts sign --input {out_path} --output {out_path} --mode anyone")
